# Generated by Django 5.1.2 on 2025-08-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='texto_extraido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
